### ISSUE TITLE
i18n : version allemande et italienne

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-sparnatural#2]
Notre[ instance demo de Sparnatural](https://sparnatural.eu/demos/demo-sapa/) ne propose une interface qu'en français et anglais. Est-ce que le version allemande et italienne sont disponibles?
Sinon, serait-il de publier les termes sur un outil en ligne de traduction collaborative afin que nous puissions examiner le travail nécessaire pour les établir ?

**Comment by b2d3c** [comment]
Cher @tfrancart, nous avons oublié de parler cet aspect traduction en italien et allemand de l'interface, ce qui est très importante pour nous. 

Comment procéder ?

Est-ce qu'un mandat spécifique serait nécessaire ?

**Comment by tfrancart** [comment]
- Nous ferons très probablement un autre tableau de spécification pour Sparnatural
- Dans cet autre tableau il y aura des colonnes de libellé et de description en français, anglais, italien et allemand
- Vous pourrez renseigner ces colonnes (je peux faire le français et l'anglais, mais pas l'italien et l'allemand). Avez-vous des personnes susceptibles de les renseigner en traduisant depuis le français ou l'anglais ?

**Comment by b2d3c** [comment]
Je pensais plus précisément aux textes de l'outil en lui-même comme "Afficher/Masquer éditeur SPARQL  |   [ Partager](https://sparnatural.eu/demos/demo-sapa/#)  |   [ Exporter la requête en JSON](https://sparnatural.eu/demos/demo-sapa/#)  |   [ Charger une requête en JSON](https://sparnatural.eu/demos/demo-sapa/#)]

**Comment by tfrancart** [comment]
> Je pensais plus précisément aux textes de l'outil en lui-même comme "Afficher/Masquer éditeur SPARQL

Ha oui pardon. La page web prévoit déjà un affichage multilingue (pour l'instant anglais/français). Il est facile d'ajouter d'autres libellés, il faudra me fournir les traductions des libellés suivants:

```javascript

      $.i18n().load( {
          'en': {
            'page.title': 'SAPA Collections',
            'menu.home': 'Sparnatural',
            'menu.lang': 'Lang.',
            'menu.github': 'Github',
            'endpoint.querying': 'Querying',
            'actions.toggle': 'Toggle SPARQL editor',
            'actions.share': 'Share',            
            'actions.export': 'Export query in JSON',
            'actions.import': 'Import query in JSON',
            'tutorial': 'First time here ? watch the tutorial !',
            'share.modal.title': 'Direct query link',
            'share.modal.close': 'Close',
            'export.modal.title': 'Query as JSON',
            'export.modal.close': 'Close',
            'import.modal.title': 'Query as JSON',
            'import.modal.import': 'Import',
            'example.placeholder': 'Load example query...',
            'example.1.title': 'Exemple 1 à compléter...',
            'example.2.title': 'Exemple 2 à compléter...'
          },
          'fr': {
            'page.title': 'SAPA Collections',
            'menu.home': 'Sparnatural',
            'menu.lang': 'Lang.',
            'menu.github': 'Github',
            'endpoint.querying': 'Service SPARQL:',
            'actions.toggle': 'Afficher/Masquer éditeur SPARQL',
            'actions.share': 'Partager',            
            'actions.export': 'Exporter la requête en JSON',
            'actions.import': 'Charger une requête en JSON',
            'tutorial': 'Vous ne savez pas comment commencer ? cliquez ici pour être guidé !',
            'share.modal.title': 'Lien direct vers la requête',
            'share.modal.close': 'Fermer',
            'export.modal.title': 'Requête JSON',
            'export.modal.close': 'Fermer',
            'import.modal.title': 'Charger une requête en JSON',
            'import.modal.import': 'Charger',
            'example.placeholder': 'Charger une requête d\'exemple...',
            'example.1.title': 'Example 1 to be completed...',
            'example.2.title': 'Example 2 to be completed...'
          }
      } );  
```

**Comment by b2d3c** [comment]
Cher @tfrancart 
Ma collègue a établi la traduction. 
[Sparnatural_traduction.xlsx](https://github.com/sapa/performing-arts-ch-sparnatural/files/14433940/Sparnatural_traduction.xlsx)

**Comment by tfrancart** [comment]
Bonjour ces traductions additionnelles ont été intégrées dans la page de démo.
Il manquera les traductions pour les titres des requêtes d'exemple que vous voudrez ajouter dans la liste déroulante, il faudra me les fournir en même temps que les requêtes d'exemple.
Les libellés de l'interface Sparnatural seront eux à mettre dans le tableau Excel de configuration (que nous referons sans doute plus tard pour avoir une config spécifique Sparnatural)

![image](https://github.com/sapa/performing-arts-ch-sparnatural/assets/2728945/b3f5f105-7da9-4ca0-86bc-021cde761acd)

**Comment by b2d3c** [comment]
Parfait! Merci.
